-- =====================================================================
-- TABBER: Supabase Database Schema & Starter Seed
-- Run this script in your Supabase Project -> SQL Editor
-- =====================================================================

-- 1. Create the 'tabs' table
CREATE TABLE IF NOT EXISTS public.tabs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    artist TEXT NOT NULL,
    tuning TEXT NOT NULL DEFAULT 'Standard (E A D G B E)',
    capo INT DEFAULT 0,
    difficulty TEXT NOT NULL DEFAULT 'Intermediate',
    content TEXT NOT NULL,
    is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Create search & filter indexes
CREATE INDEX IF NOT EXISTS idx_tabs_artist ON public.tabs (artist);
CREATE INDEX IF NOT EXISTS idx_tabs_difficulty ON public.tabs (difficulty);
CREATE INDEX IF NOT EXISTS idx_tabs_favorite ON public.tabs (is_favorite);
CREATE INDEX IF NOT EXISTS idx_tabs_updated_at ON public.tabs (updated_at DESC);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.tabs ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies to allow public read, insert, update, and delete
-- (You can later restrict these when adding Supabase User Authentication)
DROP POLICY IF EXISTS "Allow public read access" ON public.tabs;
CREATE POLICY "Allow public read access" 
ON public.tabs FOR SELECT 
USING (true);

DROP POLICY IF EXISTS "Allow public insert access" ON public.tabs;
CREATE POLICY "Allow public insert access" 
ON public.tabs FOR INSERT 
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update access" ON public.tabs;
CREATE POLICY "Allow public update access" 
ON public.tabs FOR UPDATE 
USING (true);

DROP POLICY IF EXISTS "Allow public delete access" ON public.tabs;
CREATE POLICY "Allow public delete access" 
ON public.tabs FOR DELETE 
USING (true);

-- 5. Seed Starter Guitar Tabs
INSERT INTO public.tabs (title, artist, tuning, capo, difficulty, content, is_favorite)
VALUES
(
    'Take Me Home, Country Roads',
    'John Denver',
    'Standard (E A D G B E)',
    2,
    'Beginner',
    '[Verse 1]
[G]Almost heaven, [Em]West Virginia
[D]Blue Ridge Mountains, [C]Shenandoah [G]River
[G]Life is old there, [Em]older than the trees
[D]Younger than the mountains, [C]growin'' like a [G]breeze

[Chorus]
Country [G]roads, take me [D]home
To the [Em]place I be[C]long
West Vir[G]ginia, mountain [D]mama
Take me [C]home, country [G]roads

[Verse 2]
[G]All my memories [Em]gather ''round her
[D]Miner''s lady, [C]stranger to blue [G]water
[G]Dark and dusty, [Em]painted on the sky
[D]Misty taste of moonshine, [C]teardrop in my [G]eye

[Bridge]
[Em]I hear her [D]voice in the [G]mornin'' hour, she calls me
The [C]radio re[G]minds me of my [D]home far away
And [Em]drivin'' down the [F]road, I get a [C]feelin''
That I [G]should have been home [D]yesterday, yester[D7]day
',
    TRUE
),
(
    'Knockin'' on Heaven''s Door',
    'Bob Dylan',
    'Standard (E A D G B E)',
    0,
    'Beginner',
    '[Intro]
[G]   [D]   [Am]
[G]   [D]   [C]

[Verse 1]
[G]Mama, take this [D]badge off of [Am]me
[G]I can''t [D]use it any[C]more
[G]It''s gettin'' [D]dark, too dark to [Am]see
[G]I feel I''m [D]knockin'' on heaven''s [C]door

[Chorus]
[G]Knock, knock, [D]knockin'' on heaven''s [Am]door
[G]Knock, knock, [D]knockin'' on heaven''s [C]door
[G]Knock, knock, [D]knockin'' on heaven''s [Am]door
[G]Knock, knock, [D]knockin'' on heaven''s [C]door
',
    TRUE
),
(
    'Wish You Were Here (Intro)',
    'Pink Floyd',
    'Standard (E A D G B E)',
    0,
    'Beginner',
    '[Intro Acoustic Riff]

   Em7                  G
e|-------------------|-------------------|
B|-------3-----------|-------3-----------|
G|-------0-----------|-------0-----------|
D|---0h2---2p0-------|---0h2---2p0-------|
A|-------------2-----|-------------2-----|
E|-------------------|---------------3---|

   Em7                  A7sus4
e|-------------------|-------------------|
B|-------3-----------|-------3-----------|
G|-------0-----------|-------0-----------|
D|---0h2---2p0-------|---0h2---2p0-------|
A|-------------2-----|-------------0-----|
E|-------------------|-------------------|

   Em7                  G
e|-------------------|-------------------|
B|-------3-----------|-------3-----------|
G|-------0-----------|-------0-----------|
D|---0h2---2p0-------|---0h2---2p0-------|
A|-------------2-----|-------------------|
E|-------------------|---3---------------|

[Verse]
So, [C]so you think you can [D]tell
Heaven from [Am]hell, blue skies from [G]pain
Can you tell a green [D]field from a cold steel [C]rail?
A smile from a [Am]veil? Do you think you can [G]tell?
',
    TRUE
),
(
    'Blackbird (Intro)',
    'The Beatles',
    'Standard (E A D G B E)',
    0,
    'Intermediate',
    '[Intro - Fingerstyle]

   G                 Am7               G/B
e|-------|---------|-------|---------|-------|---------|
B|---0---|-----0---|---1---|-----1---|---3---|-----3---|
G|-------|---0-----|-------|---0-----|-------|---0-----|
D|-------|---------|-------|---------|-------|---------|
A|-------|---------|---0---|---------|---2---|---------|
E|---3---|---------|-------|---------|-------|---------|

   G                     C
e|-------|-------------|-------|---------|
B|--12---|------12-----|---5---|-----5---|
G|-------|---0---------|-------|---0-----|
D|-------|-------------|-------|---------|
A|--10---|-------------|---3---|---------|
E|-------|-------------|-------|---------|
',
    TRUE
);

